algoritmo "Estrutura De Repetição (Enquanto)03"
var
   contador, valor, salto: inteiro
   
inicio
      escreva ("Me fale o numero que você deseja que seja contado? ")
      leia (valor)
      escreva ("Qual será o valor do salto?")
      leia (salto)
      contador <- 0
      enquanto (contador <= valor ) faca
      escreval (contador )
               contador <- contador + salto
      fimenquanto
      escreval ("terminei de contar ")
fimalgoritmo