algoritmo "Primeiro projeto"
var
   nome: caractere
   idade: caractere
   Celular: caractere
   Endereco: caractere
   gmail: caractere
   Documento: caractere
inicio
      escreva ("Informe seu nome completo: ")
      leia (nome)
      escreva ("Informe sua idade atual: ")
      leia (idade)
      escreva ("Informe seu Email: ")
      leia (gmail)
      escreva ("Informe seu numero de telefone: ")
      leia (celular)
      escreva ("Informe seu documento: ")
      leia (documento)
      escreva ("Informe seu endereço: ")
      leia (endereco)
      escreval ("Parabens seu cadastro foi feito com sucesso, confirme se esta tudo corretamente?" )
      escreval ("nome: ", nome)
      escreval ("Idade: ", idade, " Anos")
      escreval ("Telefone: ", celular)
      escreval ("endereço: ", endereco)
      escreval ("email: ", gmail)
      escreva ("Documento: ", documento)
fimalgoritmo