algoritmo "Primeiro projeto"
var
   nome: caractere
   idade: inteiro
   celular: caractere
   endereco: caractere
   email: caractere
   documento: caractere
inicio
      escreva ("Informe seu nome completo: ")
      leia (nome)
      escreva ("Informe sua idade atual: ")
      leia (idade)
      escreva ("Informe seu Email: ")
      leia (email)
      escreva ("Informe seu numero de telefone: ")
      leia (celular)
      escreva ("Informe seu documento: ")
      leia (documento)
      escreva ("Informe seu endereco: ")
      leia (endereco)
      escreval ("Parabens! Seu cadastro foi feito com sucesso.")
      escreval ("Confirme se esta tudo correto:")
      escreval ("Nome: ", nome)
      escreval ("Idade: ", idade, " Anos")
      escreval ("Telefone: ", celular)
      escreval ("Endereco: ", endereco)
      escreval ("Email: ", email)
      escreval ("Documento: ", documento)
fimalgoritmo